server {
  listen 4173;
  server_name _;
  absolute_redirect off;
  port_in_redirect off;

  root /usr/share/nginx/html;

  location = /effects {
    return 301 /effects/;
  }

  location /effects/assets/ {
    try_files $uri =404;
  }

  location /effects/ {
    try_files $uri $uri/ /effects/index.html;
  }

  location / {
    return 404;
  }
}
